name: sync_logo
permissions:
  contents: write
on:
  workflow_dispatch:

jobs:
  pull_logo:
    runs-on: ubuntu-latest
    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v4

      - name: 安装工具
        run: sudo apt update && sudo apt install -y wget unzip

      - name: sync_logo
        run: |
          # 清空本地logo文件夹
          rm -rf logo && mkdir -p logo
          # 下载远程logo仓库压缩包
          wget --timeout=20 --tries=3 https://github.com/samkolau/TVLOGO/archive/refs/heads/main.zip -O logo_temp.zip
          unzip -q logo_temp.zip

          # 递归查找所有png，全部复制到本地logo根目录（扁平化）
          find TVLOGO-main/logo -type f -name "*.png" -exec cp {} logo/ \;

          # 清理临时文件
          rm -rf logo_temp.zip TVLOGO-main

      - name: Git提交推送
        run: |
          git config --local user.name "Github Actions Bot"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add logo/
          if ! git diff --staged --quiet; then
            git commit -m "Auto sync all subfolder png logo flatten"
            git push
          fi
